### ISSUE TITLE
Run CI pipeline on Windows infrastructure

### ISSUE THREAD

**Issue by mschwager** [simplesamlphp/simplesamlphp#790]
I'd been thinking this would be a good idea for a while now. Then I noticed this (https://github.com/simplesamlphp/simplesamlphp/pull/782) PR, and now I'm further convinced we should have some kind of Windows CI pipeline similar to TravisCI.

Luckily, a great one already exists! I'm most familiar with AppVeyor: https://www.appveyor.com/

Enabling AppVeyor for this project should be as easy as signing into their website, enabling CI for this project (requires admin privileges), and putting something like the following in `.appveyor.yml`:

```
build: false
shallow_clone: false
version: '1.15.2.{build}'
platform: 'x64'
clone_folder: C:\projects\simplesamlphp

environment:
  matrix:
    - PHP_VERSION: "5.6"
    - PHP_VERSION: "7.0"
    - PHP_VERSION: "7.1"
    - PHP_VERSION: "7.2"

install:
  - ps: Invoke-WebRequest "https://raw.githubusercontent.com/ChadSikorra/ps-install-php/master/Install-PHP.ps1" -OutFile "Install-PHP.ps1"
  - ps: .\Install-PHP.ps1 -Version $Env:PHP_VERSION -Highest -Arch x64 -Extensions mbstring,intl,openssl
  - refreshenv
  - cd C:\projects\simplesamlphp
  - php -r "readfile('https://getcomposer.org/installer');" | php

before_test:
  - cd C:\projects\simplesamlphp
  - php composer.phar install --no-interaction --no-progress --optimize-autoloader --prefer-source --no-ansi

test_script:
  - cd C:\projects\simplesamlphp
  - vendor\bin\phpunit.bat --configuration tools/phpunit/
```

This project (https://github.com/ChadSikorra/ps-install-php) makes running PHP builds on AppVeyor dead simple :)
